# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-04-08 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_barcode_to_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_weight',
            field=models.BooleanField(default=False, verbose_name='Peso Promedio'),
        ),
    ]
