# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-08-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_exit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseexitpallet',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20, verbose_name='Gross Weight'),
        ),
        migrations.AlterField(
            model_name='warehouseexitpallet',
            name='invoice_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Entrance Invoice Weight'),
        ),
        migrations.AlterField(
            model_name='warehouseexitpallet',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20, verbose_name='Net Weight'),
        ),
        migrations.AlterField(
            model_name='wexitconfirmation',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Gross Weight'),
        ),
        migrations.AlterField(
            model_name='wexitconfirmation',
            name='invoice_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name='Invoice Weight'),
        ),
        migrations.AlterField(
            model_name='wexitconfirmation',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Net Weight'),
        ),
    ]
