# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-12-26 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_exit', '0004_auto_20211226_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='wexitproductmeasurement',
            name='werehouse_entrance_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Warehouse Entrance'),
        ),
    ]
