# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palet_lot', models.CharField(max_length=255, verbose_name='Palet Lot')),
                ('boxes', models.FloatField(blank=True, default=0, null=True, verbose_name='Boxes')),
                ('reserve_boxes', models.FloatField(blank=True, default=0, null=True, verbose_name='Reserve Boxes')),
                ('motive_to_reserve', models.CharField(choices=[('CADU', 'Caducado'), ('DAOP', 'dano de operacion'), ('MUES', 'muestras'), ('CAIN', 'caja incompleta'), ('DAOC', 'dano oculto'), ('CLIE', 'cliente'), ('DEVO', 'devolucion'), ('FADO', 'falta de documentos TIF'), ('NOID', 'producto no identificado'), ('OTRO', 'otro'), ('DEST', 'destruccion'), ('CUAR', 'cuarentena'), ('Por Inventario', 'Por Inventario')], max_length=255, verbose_name='Motive to reserve')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('released_store_box', models.FloatField(blank=True, default=0, null=True, verbose_name='Reserve Stored Boxes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveInventoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_boxes', models.FloatField(blank=True, default=0, null=True, verbose_name='Reserve Boxes')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
