# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-02 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserve_inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='reserveinventorylog',
#            name='inventory',
#            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInventory', verbose_name='Inventario de almacen'),
#        ),
#        migrations.AddField(
#            model_name='reserveinventorylog',
#            name='reserveinventory',
#            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve_inventory.ReserveInventory', verbose_name='Inventario de almacen'),
#        ),
#        migrations.AddField(
#            model_name='reserveinventorylog',
#            name='user',
#            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
#        ),
#        migrations.AddField(
#            model_name='reserveinventory',
#            name='inventory',
#            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInventory', verbose_name='Inventario de almacen'),
#        ),
    ]
