# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_entrance', '0001_initial'),
        ('maniobras', '0001_initial'),
    ]

    operations = [
    migrations.AddField(
            model_name='inventorypesovariable',
            name='werehouse_entrance_pallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WarehouseEntrancePallet', verbose_name='Warehouse Entrance Pallet'),
        )
        ]
	# migrations.CreateModel(
 #            name='InventoryPesoVariable',
 #            fields=[
 #                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
 #                ('peso_variable_quantity', models.FloatField(blank=True, default=0, null=True, verbose_name='Peso Variable Quantity')),
 #                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
 #                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
 #                ('werehouse_entrance_pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WarehouseEntrancePallet', verbose_name='Warehouse Entrance Pallet')),
 #            ],
 #        ),
 #    ]
