# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maniobras', '0003_takinginventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorypesovariable',
            name='werehouse_entrance_pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WarehouseEntrancePallet', verbose_name='Warehouse Entrance Pallet'),
        ),
    ]
