# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_entrance', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='warehouseinventory',
#            name='warehouse_entrance_pallet',
#            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WarehouseEntrancePallet'),
#        ),
#        migrations.AddField(
#            model_name='warehouseinventory',
#            name='warehouse_location',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseLocation'),
#        ),
#        migrations.AddField(
#            model_name='warehouseheightlevel',
#            name='section',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseSection'),
#        ),
#        migrations.AddField(
#            model_name='warehousedepthlevel',
#            name='height',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseHeightLevel'),
#        ),
#        migrations.AddField(
#            model_name='warehousedepthlevel',
#            name='warehouse_location',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseLocation'),
#        ),
    ]
