# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-02 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import warehouses.warehouse_entrance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0001_initial'),
        ('product', '0001_initial'),
        #('clients', '0002_client_user'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrancePalletPesoVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_variable_quantity', models.FloatField(blank=True, default=0, null=True, verbose_name='Peso Variable Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseEntrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_date', models.DateField(verbose_name='Entrance Date')),
                ('entrance_hour', models.TimeField(blank=True, verbose_name='Entrance Hour')),
                ('license_plate', models.CharField(blank=True, max_length=250, null=True, verbose_name='License Plates')),
                ('total_kg', models.FloatField(blank=True, default=0, null=True, verbose_name='Total Kg')),
                ('total_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Total Price')),
                ('kg_per_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Kg Per Price')),
                ('boxes', models.FloatField(blank=True, default=0, null=True, verbose_name='Boxes')),
                ('kg_per_boxes', models.FloatField(blank=True, default=0, null=True, verbose_name='Kg Per Box')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('vehicle_temograph', models.IntegerField(default=0, verbose_name='Vehicle has Termograph')),
                ('temprature_cel', models.IntegerField(default=0, verbose_name='Temperature celcious')),
                ('cont_flr_sta', models.IntegerField(default=0, verbose_name='Container Floor Status')),
                ('fasteners', models.IntegerField(default=0, verbose_name='Fasteners')),
                ('container_clean', models.IntegerField(default=0, verbose_name='Container Clean')),
                ('inside_container_good', models.IntegerField(default=0, verbose_name='Inside The Container is in Good Condition')),
                ('loading_availity', models.BooleanField(default=0, verbose_name='ContainVehicle able for loading/unloading')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('prente', models.BooleanField(default=False, verbose_name='Frente')),
                ('lado_izquerdo', models.BooleanField(default=False)),
                ('vista_inferior', models.BooleanField(default=False)),
                ('puerta_tresera_deregha', models.BooleanField(default=False)),
                ('duerta_tresera_inquiera', models.BooleanField(default=False)),
                ('techa', models.BooleanField(default=False)),
                ('puerta_referal', models.BooleanField(default=False)),
                ('puerta', models.BooleanField(default=False)),
                ('lado_denecha', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('InManeuvers', 'In Maneuvers'), ('ManeuverComplete', 'Maneuver Complete'), ('finish', 'Finish')], default='pending', max_length=20, verbose_name='Warehouse Entrance Status')),
                ('cargo_type', models.CharField(choices=[('P', 'P'), ('A', 'A')], max_length=100, verbose_name='Cargo Type')),
                ('cargo_sender', models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo Sender')),
                ('driver_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name Of The Driver')),
                ('temp_front', models.FloatField(default=0, verbose_name='Temprature Front')),
                ('temp_middle', models.FloatField(default=0, verbose_name='Temprature Middel')),
                ('temp_back', models.FloatField(default=0, verbose_name='Temprature Back')),
                ('cust_reference', models.CharField(blank=True, default='', max_length=255, verbose_name='Referencia')),
                ('seal1', models.CharField(blank=True, default='', max_length=255, verbose_name='Fleje/Sello 1')),
                ('seal2', models.CharField(blank=True, default='', max_length=255, verbose_name='Fleje/Sello 2')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.Carrier', verbose_name='Carrier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle', verbose_name='Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseEntranceConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Code')),
                ('cost_lot', models.CharField(default='', max_length=255, verbose_name='Cust Lot')),
                ('exp_date', models.CharField(blank=True, max_length=255, verbose_name='Expiration Date')),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Gross Weight')),
                ('net_weight', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Net Weight')),
                ('invoice_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Entrance Invoice Weight')),
                ('retained_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Retained Qty')),
                ('retained_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Retainment Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseEntrancePallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palet_lot', models.CharField(blank=True, default=warehouses.warehouse_entrance.models.increment_pallet_palet_lot, max_length=255, verbose_name='Palet Lot')),
                ('boxes', models.FloatField(blank=True, default=0, null=True, verbose_name='Boxes')),
                ('cost_lot', models.CharField(default='', max_length=255, verbose_name='Cust Lot')),
                ('exp_date', models.CharField(blank=True, max_length=255, verbose_name='Expiration Date')),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Gross Weight')),
                ('net_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Net Weight')),
                ('invoice_weight', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Entrance Invoice Weight')),
                ('retained_quantity', models.IntegerField(default=0, verbose_name='Retained Qty')),
                ('retained_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Retainment Reason')),
                ('box_kg', models.FloatField(blank=True, default=0, null=True, verbose_name='Box Kg')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Pallet Confirmed')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseLocation', verbose_name='Location')),
                ('rack_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseSection', verbose_name='Rack Number')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse', verbose_name='Warehouse')),
                ('werehouse_entrance_confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WarehouseEntranceConfirmation', verbose_name='Warehouse Entrance')),
            ],
        ),
        migrations.CreateModel(
            name='WIncidenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to=b'', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('werehouse_entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WarehouseEntrance', verbose_name='Entrance')),
            ],
        ),
        migrations.CreateModel(
            name='WIncidenceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code')),
                ('incidence', models.FloatField(blank=True, default=0, null=True, verbose_name='Kg Per Price')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
                ('werehouse_entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WarehouseEntrance', verbose_name='Entrance')),
            ],
        ),
        migrations.CreateModel(
            name='WProductMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kg', models.FloatField(blank=True, default=0, null=True, verbose_name='Total Kg')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Total Price')),
                ('kg_per_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Kg Per Price')),
                ('boxes', models.FloatField(blank=True, default=0, null=True, verbose_name='Boxes')),
                ('kg_per_boxes', models.FloatField(blank=True, default=0, null=True, verbose_name='Kg Per Box')),
                ('product_description', models.CharField(max_length=60, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
                ('werehouse_entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WarehouseEntrance', verbose_name='Entrance')),
            ],
        ),
        migrations.CreateModel(
            name='WProductVehicleInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_temograph', models.IntegerField(default=0, verbose_name='Vehicle has Termograph')),
                ('temprature_cel', models.IntegerField(default=0, verbose_name='Temperature celcious')),
                ('cont_flr_sta', models.IntegerField(default=0, verbose_name='Container Floor Status')),
                ('fasteners', models.IntegerField(default=0, verbose_name='Fasteners')),
                ('container_clean', models.IntegerField(default=0, verbose_name='Container Clean')),
                ('inside_container_good', models.IntegerField(default=0, verbose_name='Inside The Container is in Good Condition')),
                ('loading_availity', models.BooleanField(default=0, verbose_name='ContainVehicle able for loading/unloading')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('werehouse_entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WarehouseEntrance', verbose_name='Entrance')),
            ],
        ),
        migrations.AddField(
            model_name='warehouseentranceconfirmation',
            name='w_product_measurement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WProductMeasurement'),
        ),
        migrations.AddField(
            model_name='warehouseentranceconfirmation',
            name='werehouse_entrance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WarehouseEntrance', verbose_name='Warehouse Entrance'),
        ),
        migrations.AddField(
            model_name='entrancepalletpesovariable',
            name='werehouse_entrance_pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_entrance.WarehouseEntrancePallet', verbose_name='Warehouse Entrance Pallet'),
        ),
    ]
