# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-11-30 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_entrance', '0003_auto_20211129_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseentrancepallet',
            name='maniobras',
            field=models.BooleanField(default=False, verbose_name='Maniobras'),
        ),
    ]
