# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-12-16 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_entrance', '0004_warehouseentrancepallet_maniobras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseentrance',
            name='boxes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Boxes'),
        ),
        migrations.AlterField(
            model_name='warehouseentrancepallet',
            name='boxes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Boxes'),
        ),
        migrations.AlterField(
            model_name='wproductmeasurement',
            name='boxes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Boxes'),
        ),
    ]
