# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-01-15 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_entrance', '0006_warehouseentrance_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wproductmeasurement',
            name='control_total_boxes',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Total Kg'),
        ),
        migrations.AddField(
            model_name='wproductmeasurement',
            name='control_total_kg',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Boxes'),
        ),
    ]
