# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-01-15 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_entrance', '0007_auto_20220115_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wproductmeasurement',
            name='control_total_boxes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Control Total Boxes'),
        ),
        migrations.AlterField(
            model_name='wproductmeasurement',
            name='control_total_kg',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Control Total Kg'),
        ),
    ]
