# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-01-24 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_warehouselocation_shortcode'),
        ('warehouse_entrance', '0008_auto_20220115_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletConsolidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Pallet')),
                ('destination_pallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination Pallet')),
                ('source_boxes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Pallet')),
                ('source_weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Pallet')),
                ('destination_boxes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Pallet')),
                ('destination_weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Pallet')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Pallet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('destination_inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_inventory', to='warehouse.WarehouseInventory', verbose_name='Destination Inventory')),
                ('source_inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_inventory', to='warehouse.WarehouseInventory', verbose_name='Source Inventory')),
            ],
        ),
    ]
