# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-03-31 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_entrance', '0009_palletconsolidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseentrance',
            name='sent_to_maniobras_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent to Maniobras At'),
        ),
        migrations.AddField(
            model_name='warehouseentrancepallet',
            name='maniobras_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Maniobras Completed At'),
        ),
    ]
