# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-03-31 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_entrance', '0010_auto_20220330_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseentrancepallet',
            name='sent_to_maniobras_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent To Maniobras'),
        ),
    ]
