# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, verbose_name='Code')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('is_baseline', models.BooleanField(default=False, help_text='Use this list as baseline price list', verbose_name='Baseline Price List')),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
            },
        ),
        migrations.CreateModel(
            name='ServiceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_list.PriceList')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Price List Item',
                'verbose_name_plural': 'Price List Items',
            },
        ),
    ]
