# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-12-10 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_relocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouserelocation',
            name='source_location',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Source Location'),
        ),
        migrations.AlterField(
            model_name='warehouserelocation',
            name='source_warehouse',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Source Warehouse'),
        ),
    ]
