# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, verbose_name='Code')),
                ('name', models.CharField(max_length=250, verbose_name='Full Name')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=255, verbose_name='Contact Phone Number')),
                ('signature', models.FileField(blank=True, upload_to=b'', verbose_name='Signature')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Customer')),
            ],
        ),
    ]
